server:
  port: 5001
spring:
  application:
    name: user.service

  datasource:
    url: jdbc:postgresql://localhost:5432/airline_location_db
    username: root
    password: 1

  jpa:
    hibernate:
      ddl-auto: update